class Constants(object):
    BOARD_WIDTH = 10
    BOARD_HEIGHT = 10

    FPS = 15

    SESSIONS_COUNT = 30
    SESSION_REFRESH_INTERVAL = 0

    FOOD_COUNT = 1
    HUNGER_LIMIT = 15

    INPUT_NEURONS_COUNT = 8
    HIDDEN_NEURONS_COUNT = 16
    OUTPUT_NEURONS_COUNT = 4

    GENE_RESOLUTION = 16
    MUTATION_RATIO = 10

    BEST_GAMES_BREED_COUNT = 4
    RANDOM_GAMES_BREED_COUNT = 2