class Constants(object):
    BOARD_WIDTH = 20
    BOARD_HEIGHT = 20

    FPS = 30

    SESSIONS_COUNT = 10
    SESSION_REFRESH_INTERVAL = 0

    FOOD_COUNT = 15
    HUNGER_LIMIT = 50

    INPUT_NEURONS_COUNT = 8
    HIDDEN_NEURONS_COUNT = 8
    OUTPUT_NEURONS_COUNT = 4

    GENE_RESOLUTION = 16
    MUTATION_RATIO = 5